### ISSUE TITLE
ORDER meta _groupid

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#107]
The following example query: 
D = SELECT(region: chr == chr1) Example_Dataset_1;
RES = ORDER(cell_sex, cell; meta_topg: 1; region_order: qvalue, score; region_topg: 2) D;
MATERIALIZE RES INTO order_6;
adds metadata _order_groupId (besides metadata _order); is it useful? Doesn't suffice the metadata _order to identify the group? (this is a minor, anyway)

Furthermore, in the case of the following query (meta_topp) also the metadata _order_groupId is added, but the metadata _order is not added:
D = SELECT(region: chr == chr1) Example_Dataset_1;
RES = ORDER(avg_score DESC; meta_topp: 70) D;
MATERIALIZE RES INTO order_4;
In this case (meta_topp) the metadata attribute _order should be added and the metadata attribute _order_groupId shouldn't be added.

**Comment by marcomass** [comment]
@pp86 @acanakoglu 
In the output metadata of ORDER(... meta_topp: ...):
- add attribute  _order 
- remove attribute  _order_groupId 

If anything is not clear, please ask.

**Comment by marcomass** [comment]
@OlgaGorlova 
Can you fix this issue?

**Comment by OlgaGorlova** [comment]
@marcomass 
I have committed my changes. I have used a query like the following one to test it:

```
DS = SELECT() Test_DS;
RES_topp = ORDER(test ASC; meta_topp: 80) DS;
RES_topg = ORDER(cell, test ASC; meta_topg: 1) DS;
MATERIALIZE RES_topp into order_topp;
MATERIALIZE RES_topg into order_topg;
```

The testing dataset [Test_DS](https://github.com/DEIB-GECO/GMQL/files/1928425/filesExp.zip) is attached.
Let me know if there are any questions.

**Comment by marcomass** [comment]
@OlgaGorlova     cc @andreagulino 
I tested on cineca where Andrea updated the system, but the issue is still there: in the output metadata RES_topp is still missing the metadata attribute _order (please add it) and is still included the attribute _order_groupId (please remove it)

**Comment by OlgaGorlova** [comment]
@marcomass I have checked the issue on both - cineca and my local machine. Locally it is working as expected. Maybe cineca is not updated.
@andreagulino I pushed my changes to master branch. I am not sure why it is not working on cineca. Do I have to make some changes anywhere else?

**Comment by marcomass** [comment]
Fixed.
